case_neoway:
  outputs:
    dev:
      dataset: schema
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials.json
      location: US
      method: service-account
      priority: interactive
      project: case-neoway-434216
      threads: 1
      type: bigquery
  target: dev
